[project]
name = "lm-dw-deezer"
version = "0.0.2b11"
description = "Liberum Melodian Library for making easy tracks downloading from Deezer"
license = "CC BY 4.0"
readme = "README.md"
repository = "https://github.com/An0nimia/lm_dw_deezer"
requires-python = ">=3.12,<4.0"
authors = [
	{ name = "An0nimia", email = "an0nimia@protonmail.com" },
]
dependencies = [
	"requests (>=2.32.4,<3.0.0)",
	"pydantic (>=2.11.7,<3.0.0)",
	"pycryptodomex (>=3.23.0,<4.0.0)",
	"mutagen (>=1.47.0,<2.0.0)",
	"tqdm (>=4.67.1,<5.0.0)",
	"typer[all] (>=0.16.0,<0.17.0)",
	"inquirerpy (>=0.3.4,<0.4.0)",
	"zstandard (>=0.23.0,<0.24.0)",
	"api-deezer-full (>=0.0.1b41,<0.0.2)",
]

[project.optional-dependencies]
RUSTDW = ["lm-deezer-bf-dec (>=0.0.1b4,<0.0.2)"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[project.scripts]
lm_dw_deezer = "lm_dw_deezer.exes.cli:main"
