name: Publish to Docker Hub

on:
  push:
    branches:
      - "release"
  workflow_dispatch:

env:
  LATEST_TAG: an0nimia/lm_dw_deezer:latest

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_LM_DW_DEEZER_USER }}
          password: ${{ secrets.DOCKER_LM_DW_DEEZER_PASS }}
      - name: Build and export to Docker
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:docker"
          load: true
          tags: ${{ env.LATEST_TAG }}
      - name: Test
        run: |
          docker run --rm ${{ env.LATEST_TAG }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:docker"
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.LATEST_TAG }}